"""
consolidar_mes.py

Merges the partial CSV files generated by descargar_historicos.py
into a single consolidated file per month.

Each month is downloaded in batches by substation letter (CD, LM, PS).
This script combines those batches, removes duplicates, and outputs
one clean file per month ready to load into MySQL.

Usage: Update the file list and output filename for the target month.
Example shown uses October 2025 (month 10). Change the filenames
accordingly for any other month.
"""

import pandas as pd

archivos = [
    'inyeccion_2025_10_parte_CD.csv',
    'inyeccion_2025_10_parte_LM.csv',
    'inyeccion_2025_10_parte_PS.csv',
]

dfs = [pd.read_csv(f) for f in archivos]
df_final = pd.concat(dfs, ignore_index=True)
df_final = df_final.drop_duplicates(subset=['fecha', 'hora', 'medidor'])
df_final.to_csv('inyeccion_2025_10.csv', index=False)

print(f"Total records: {len(df_final)}")
print(f"Meters: {sorted(df_final['medidor'].unique())}")
print(f"Saved: inyeccion_2025_10.csv")
